#!/usr/bin/env bash
#
# fuzz.sh — differential test for TEMU's expression evaluator.
#
# For each random expression generated by gen-expr, compile it as a C
# program, run it, and use the output as the ground truth. Feed the
# same expression to `temu -t` and compare. Any mismatch is a parser
# or evaluator bug.
#
# Expressions that the host C compiler refuses (extremely rare given
# the restricted operator set) or whose binary exits with a non-zero
# status are silently skipped rather than counted as failures.

set -u

N=${1:-200}
SELF_DIR=$(cd "$(dirname "$0")" && pwd)
ROOT=$(cd "$SELF_DIR/../.." && pwd)

TOOL=$ROOT/build/tools/gen-expr/gen-expr
TEMU=$ROOT/build/temu

if [[ ! -x $TOOL ]]; then
    echo "gen-expr binary missing. Run: make" >&2
    exit 2
fi
if [[ ! -x $TEMU ]]; then
    echo "temu binary missing. Run: make" >&2
    exit 2
fi

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

SRC=$TMPDIR/probe.c
BIN=$TMPDIR/probe
EXPRS=$TMPDIR/exprs.txt
TESTFILE=$TMPDIR/tests.txt

"$TOOL" "$N" > "$EXPRS"

verified=0
skipped=0
: > "$TESTFILE"

while IFS= read -r EXPR; do
    {
        printf '#include <stdio.h>\n'
        printf '#include <stdint.h>\n'
        printf 'int main(void) {\n'
        printf '    uint32_t r = (uint32_t)(%s);\n' "$EXPR"
        printf '    printf("%%u\\n", r);\n'
        printf '    return 0;\n'
        printf '}\n'
    } > "$SRC"

    if ! cc -w -O0 -o "$BIN" "$SRC" 2>/dev/null; then
        skipped=$((skipped + 1))
        continue
    fi

    if ! expected=$("$BIN" 2>/dev/null); then
        skipped=$((skipped + 1))
        continue
    fi

    # Strip the 'u' literal suffix before handing the expression to TEMU:
    # the suffix exists only to force unsigned arithmetic on the host C
    # side. Our operator set contains no other 'u' characters, so a blind
    # global strip is safe.
    TEMU_EXPR=${EXPR//u/}
    printf '%s\t%s\n' "$expected" "$TEMU_EXPR" >> "$TESTFILE"
    verified=$((verified + 1))
done < "$EXPRS"

echo "fuzz: generated=$N  verified=$verified  skipped=$skipped"

if [[ $verified -eq 0 ]]; then
    echo "no usable test cases were produced — aborting" >&2
    exit 2
fi

"$TEMU" -t "$TESTFILE"
